In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("PCA_Training.csv")
df.head()
dataset_size = df.size

In [3]:
mean_X = np.mean(df["X"])
mean_Y = np.mean(df["Y"])

In [4]:
zero_mean_x = df["X"]-mean_X
zero_mean_y = df["Y"]-mean_Y
zero_mean_array = np.column_stack((zero_mean_x,zero_mean_y))
zero_mean_array

array([[ 0.69,  0.49],
       [-1.31, -1.21],
       [ 0.39,  0.99],
       [ 0.09,  0.29],
       [ 1.29,  1.09],
       [ 0.49,  0.79],
       [ 0.19, -0.31],
       [-0.81, -0.81],
       [-0.31, -0.31],
       [-0.71, -1.01]])

In [5]:
covariance_matrix = np.zeros((2,2))
covariance_matrix

array([[ 0.,  0.],
       [ 0.,  0.]])

In [24]:
covariance_matrix = np.cov((df["X"],df["Y"]))
covariance_matrix

array([[ 0.61655556,  0.61544444],
       [ 0.61544444,  0.71655556]])

In [25]:
eig_vals, eig_vecs = np.linalg.eig(covariance_matrix)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]

Eigenvalues 
[ 0.0490834   1.28402771]


In [26]:
transpose_eign_vector = eig_vecs.transpose()
transpose_eign_vector

array([[-0.73517866,  0.6778734 ],
       [-0.6778734 , -0.73517866]])

In [27]:
transpose_zero_mean_array = zero_mean_array[:].transpose()
transpose_zero_mean_array

array([[ 0.69, -1.31,  0.39,  0.09,  1.29,  0.49,  0.19, -0.81, -0.31,
        -0.71],
       [ 0.49, -1.21,  0.99,  0.29,  1.09,  0.79, -0.31, -0.81, -0.31,
        -1.01]])

In [28]:
final_data = np.dot(transpose_eign_vector,transpose_zero_mean_array)

In [29]:
final_data

array([[-0.17511531,  0.14285723,  0.38437499,  0.13041721, -0.20949846,
         0.17528244, -0.3498247 ,  0.04641726,  0.01776463, -0.16267529],
       [-0.82797019,  1.77758033, -0.99219749, -0.27421042, -1.67580142,
        -0.9129491 ,  0.09910944,  1.14457216,  0.43804614,  1.22382056]])

In [36]:
new_final_data = final_data.transpose()
new_final_data = new_final_data[:,[1,0]]
new_final_data

array([[-0.82797019, -0.17511531],
       [ 1.77758033,  0.14285723],
       [-0.99219749,  0.38437499],
       [-0.27421042,  0.13041721],
       [-1.67580142, -0.20949846],
       [-0.9129491 ,  0.17528244],
       [ 0.09910944, -0.3498247 ],
       [ 1.14457216,  0.04641726],
       [ 0.43804614,  0.01776463],
       [ 1.22382056, -0.16267529]])